name: Node.js Package


on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          registry-url: https://npm.pkg.github.com/
          scope: '@stoyanov-ivelin'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      
